"use strict";
// Class 3: canonical API, owned disposable database, fake provider fence only.
const assert=require('node:assert/strict'),fs=require('node:fs'),{randomUUID}=require('node:crypto');
const boundary=require('../e2e/proof_boundary');require('../e2e/proof_fence_preload');
const {Pool}=require('pg'),sessions=require('../../src/identity/staff_session_service');
(async()=>{
 await boundary.assertDatabase();const pool=new Pool({connectionString:boundary.manifest().url,ssl:false});
 const one=async(s,a=[])=>(await pool.query(s,a)).rows[0];let n=0;
 const check=(v,label)=>{assert(v,label);console.log('PASS '+label);n++;};
 try{
  const p=await one("select id from properties where name='Skyline E2E' order by created_at desc limit 1"),tag=randomUUID();assert(p);
  await pool.query("update properties set operating_timezone='America/New_York' where id=$1",[p.id]);
  const person=await one("insert into persons(name) values('Owned tour staff') returning id");
  const user=await one("insert into users(name,role,is_active,status,account_kind,person_id) values('Owned tour staff','leasing_agent',true,'active','human_staff',$1) returning id",[person.id]);
  await pool.query("insert into property_team_assignments(user_id,property_id,role_title,allowed_modules,primary_for_modules,active) values($1,$2,'Leasing Agent','{leasing}','{leasing}',true)",[user.id,p.id]);
  await pool.query("insert into assignments(person_id,property_id,role,is_active) values($1,$2,'leasing',true)",[person.id,p.id]);
  const s=await sessions.issueStaffSession(pool,{userId:user.id,propertyId:p.id,purpose:'bootstrap_invite'}),token=s.session_token||s.token;
  const req=async(method,path,body,auth=token)=>{const r=await fetch(process.env.E2E_API_BASE+path,{method,headers:{'content-type':'application/json',...(auth?{'x-staff-session':auth}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};
  const source='Owned tour '+tag;await pool.query("insert into lead_sources(name,source_type) values($1,'website')",[source]);
  const inquiry=async()=>{const r=await fetch(process.env.E2E_API_BASE+'/leasing/intake',{method:'POST',headers:{'content-type':'application/json','x-intake-secret':'e2e-intake'},body:JSON.stringify({property_id:p.id,name:'Owned future tour',email:randomUUID()+'@example.invalid',source,attempt_sms:false,sms_consent:false,response_channel:'website'})});assert.equal(r.status,200);const b=await r.json();b.conversation_id=(await one('select id from conversations where property_id=$1 and person_id=$2',[p.id,b.person_id])).id;return b;};
  const policy=await one('select minimum_notice_minutes from tour_schedule_policies where property_id=$1 and active=true',[p.id]);
  let hour=Math.max(25,Math.ceil(Number(policy?.minimum_notice_minutes||0)/60)+1);
  const slot=async({property=p.id,host=user.id,when=null,status='open'}={})=>{const start=when||new Date(Date.now()+(hour++)*3600000).toISOString();return one("insert into tour_availability(property_id,leasing_agent_id,starts_at,ends_at,status,capacity) values($1,$2,$3,$4,$5,1) returning *",[property,host,start,new Date(new Date(start).getTime()+1800000).toISOString(),status]);};
  const lead=await inquiry(),a=await slot(),b=await slot(),key=randomUUID();
  const route=id=>`/operator/leasing/conversations/${id}/book-tour`;
  const book=(who,time,k=randomUUID(),auth=token,extra={})=>req('POST',route(who.conversation_id),{slot_id:time.id,idempotency_key:k,...extra},auth);
  check((await req('POST',`/operator/conversations/${lead.conversation_id}/take-over`,{})).status===200,'inquiry is claimed through authentic staff session');
  const before=await one('select current_review_obligation_id from agent_thread_state where conversation_id=$1',[lead.conversation_id]);
  const sms=()=>fs.existsSync(process.env.E2E_SMS_LOG||'')?fs.readFileSync(process.env.E2E_SMS_LOG,'utf8'):'';const smsBefore=sms();
  check((await book(lead,a,key,null)).status===401,'anonymous booking is refused');
  check((await req('POST',route(lead.conversation_id),{slot_id:a.id})).status===400,'missing request identity is refused');
  const booked=await book(lead,a,key,token,{actor_id:randomUUID(),property_id:randomUUID(),person_id:randomUUID()});
  check(booked.status===200,`staff session books native future slot without operator key: ${JSON.stringify(booked)}`);
  const tour=await one('select * from leasing_tours where id=$1',[booked.body.tour_id]);
  check(tour.lead_id===lead.lead_id&&tour.property_id===p.id&&tour.slot_id===a.id&&tour.leasing_agent_id===user.id,'canonical tour retains exact inquiry property slot and host');
  const event=await one("select * from tour_events where tour_id=$1 and event_type='scheduled'",[tour.id]);
  check(event.actor_id===user.id&&event.actor_type==='human'&&event.metadata.subject_person_id===lead.person_id,'server staff actor stays distinct from prospect subject');
  check(sms()===smsBefore&&/No confirmation message/.test(booked.body.receipt),'booking dispatches no confirmation');
  check((await one('select current_review_obligation_id from agent_thread_state where conversation_id=$1',[lead.conversation_id])).current_review_obligation_id===before.current_review_obligation_id&&(await one('select status from obligations where id=$1',[before.current_review_obligation_id])).status==='in_progress','booking does not silently finish inquiry work');
  const replay=await book(lead,a,key);check(replay.status===200&&replay.body.idempotent&&replay.body.tour_id===tour.id,'exact replay returns the same tour');
  check((await book(lead,b,key)).status===409,'changed slot with same request identity is refused');
  check((await book(lead,b)).status===409,'same inquiry cannot acquire another upcoming tour');
  const other=await inquiry();check((await book(other,a)).status===409,'competing inquiry cannot book occupied slot');
  check((await book(other,{id:randomUUID()})).status===404,'missing slot is explicit');
  const past=await slot({when:new Date(Date.now()-3600000).toISOString()});check((await book(other,past)).status===409,'past time is refused');
  const closed=await slot({status:'blocked'});check((await book(other,closed)).status===409,'closed slot is refused');
  const foreign=await one("insert into properties(name,operating_timezone) values($1,'America/New_York') returning id",['Owned foreign '+tag]),foreignSlot=await slot({property:foreign.id,host:null});
  check((await book(other,foreignSlot)).status===404,'foreign property slot is refused');
  const foreignConv=await one('insert into conversations(person_id,property_id) values($1,$2) returning id',[other.person_id,foreign.id]);
  check((await book({conversation_id:foreignConv.id},a,key)).status===403,'conversation property authority is checked before replay');
  const inactive=await one("insert into users(name,role,is_active,status,account_kind) values('Owned inactive host','leasing_agent',false,'active','human_staff') returning id");
  await pool.query("insert into property_team_assignments(user_id,property_id,role_title,allowed_modules,active) values($1,$2,'Leasing Agent','{leasing}',true)",[inactive.id,p.id]);
  check((await book(other,await slot({host:inactive.id}))).status===409,'host current active eligibility is rechecked');
  await pool.query("update property_team_assignments set allowed_modules='{maintenance}' where user_id=$1 and property_id=$2",[user.id,p.id]);
  check((await book(lead,a,key)).status===403,'leasing module entitlement is checked before replay');
  await pool.query("update property_team_assignments set allowed_modules='{leasing}' where user_id=$1 and property_id=$2",[user.id,p.id]);
  await pool.query('update properties set operating_timezone=null where id=$1',[p.id]);check((await book(other,b)).status===409,'unconfigured timezone is refused');
  await pool.query("update properties set operating_timezone='America/New_York' where id=$1",[p.id]);
  await pool.query('update users set is_active=false where id=$1',[user.id]);check((await book(lead,a,key)).status===401,'revoked staff authority is checked before replay');
  await pool.query('update users set is_active=true where id=$1',[user.id]);
  const competing=await slot(),c1=await inquiry(),c2=await inquiry();
  const race=await Promise.all([book(c1,competing),book(c2,competing)]);check(race.map(x=>x.status).sort().join(',')==='200,409','concurrent requests book one slot once');
  check((await one('select count(*)::int n from leasing_tours where slot_id=$1',[competing.id])).n===1,'concurrent slot booking retains one canonical tour');
  const same=await inquiry(),left=await slot(),right=await slot();
  const sameRace=await Promise.all([book(same,left),book(same,right)]);
  check(sameRace.map(x=>x.status).sort().join(',')==='200,409','competing slots for one inquiry create only one future appointment');
  // Actual outcome is a separate human statement, through the existing completion owner.
  const completed=await req('POST',`/operator/leasing/tours/${tour.id}/complete`,{actual_tour_host_user_id:user.id,feedback:{standing:'possible',notes:'Owned outcome capture'},idempotency_key:randomUUID()});
  check(completed.status===200,`existing staff completion captures outcome: ${JSON.stringify(completed)}`);
  const conversion=await one('select * from leasing_conversions where person_id=$1 and property_id=$2 and status=\'active\'',[lead.person_id,p.id]);
  check(!!conversion,'actual outcome creates canonical conversion standing');
  const next=await one("select o.* from leasing_conversion_obligations l join obligations o on o.id=l.obligation_id where l.conversion_id=$1 and o.status!='complete' order by o.created_at desc limit 1",[conversion.id]);
  check(!!next&&next.assigned_user_id===user.id,'post-tour next work records accountable eligible staff');
  if(process.env.E2E_TOUR_FIXTURE_OUTPUT)fs.writeFileSync(process.env.E2E_TOUR_FIXTURE_OUTPUT,JSON.stringify({api:process.env.E2E_API_BASE,property_id:p.id,user_id:user.id,session:token,inquiry:other,slot:b}));
  console.log(`RESULT ${n}/${n}`);
 }finally{await pool.end()}
})().catch(e=>{console.error(e);process.exitCode=1});
