"use strict";
// Class3: existing owned fixture, real offer HTTP door; no provider calls or tour-birth claim.
const assert=require('node:assert/strict');
module.exports=async({c,f,session,start,end,previousDay})=>{
 const home=f.units['B-upcoming'],alternative=f.units['A-marketable'];
 const person=(await c.query("insert into persons(name,lifecycle_status) values('Owned competing-home applicant','prospect') returning id")).rows[0];
 const conv=(await c.query("insert into leasing_conversions(person_id,property_id,actual_tour_host_user_id,conversation_owner_user_id,tour_notes) values($1,$2,$3,$3,'Synthetic historical case; no tour birth claimed') returning id",[person.id,f.property_id,f.user_id])).rows[0];
 await c.query('update property_team_assignments set can_manage_roles=true where property_id=$1 and user_id=$2',[f.property_id,f.user_id]);
 const body={space_id:home.space_id,lease_start_date:start,lease_end_date:end,rent:1200,security_deposit:0,fees:[],concessions:{status:'none'},idempotency_key:'owned-competing-home'};
 const offers=async()=>Number((await c.query("select count(*) from lease_offers where property_id=$1 and person_id=$2",[f.property_id,person.id])).rows[0].count);
 const post=async(b,headers={'x-staff-session':session})=>{const r=await fetch(process.env.E2E_API_BASE+'/operator/leasing/conversions/'+conv.id+'/application-offer',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(b)});return{status:r.status,data:await r.json()};};
 const before=await offers();
 const unassigned=await post(body);assert.equal(unassigned.status,403);assert.equal(unassigned.data.error,'ACTOR_IDENTITY_UNRESOLVED');assert.equal(await offers(),before);
 await c.query("insert into assignments(person_id,property_id,role,provenance) select person_id,$2,'owner',jsonb_build_object('source','owned competing-home proof') from users where id=$1",[f.user_id,f.property_id]);
 await c.query('update leases set end_date=$2 where id=$1',[f.ids.upcoming_lease,end]);
 const denied=await post(body);assert.equal(denied.status,409,JSON.stringify(denied.data));assert.equal(denied.data.error,'application_term_not_free');assert.equal(await offers(),before,'refused term must roll back prepared offer');
 const unavailable=await post({...body,space_id:f.units['C-turnover'].space_id,idempotency_key:'owned-unknown-readiness'});assert.equal(unavailable.status,409);assert.equal(await offers(),before,'unknown readiness may not establish an offer');
 const rank=require('../../src/maintenance/turn_priority').rankTurnPriority;
 const bare=await post({...body,space_id:alternative.space_id});assert.equal(bare.status,409);assert.equal(await offers(),before,'bare inventory label must not authorize an offer');
 // Explicit second synthetic outgoing tenancy and feasible turn; no source confirmation or real resident.
 await c.query("insert into leases(property_id,space_id,lease_status,start_date,end_date,rent,tenant_ids) values($1,$2,'active',current_date-30,$3,1200,$4)",[f.property_id,alternative.space_id,previousDay,[f.person_id]]);
 await c.query("insert into unit_events(unit_id,space_id,event_type,effective_date,status) values($1,$2,'notice_given',$3,'scheduled')",[alternative.unit_id,alternative.space_id,previousDay]);
 await c.query("insert into turnovers(property_id,unit_id,status,ready_date) values($1,$2,'in_progress',$3)",[f.property_id,alternative.unit_id,start]);
 await c.query("update units set occupancy_status='occupied' where id=$1",[alternative.unit_id]);
 const diagnostic=await require('../../src/applications/application_target_authority').resolveApplicationTarget(c,{property_id:f.property_id,space_id:alternative.space_id,intended_move_in:start,requested_end:end});
 console.log('COMPETING_TARGET',{ok:diagnostic.ok,marketing_state:diagnostic.marketing_state,blocking_reason:diagnostic.blocking_reason,refusal_code:diagnostic.refusal_code});
 const competingPriority=await rank(c,f.property_id);
 const chosen=await post({...body,space_id:alternative.space_id});assert.equal(chosen.status,200,JSON.stringify(chosen.data));assert(chosen.data.application_offer_id);assert.equal(chosen.data.application_terms.target.space_id,alternative.space_id);assert.equal(chosen.data.application_terms.security_deposit,'0.00');assert.equal(await offers(),before+1);
 assert.deepEqual(await rank(c,f.property_id),competingPriority,'draft application offer must not change maintenance commitment priority');
 const duplicate=await post({...body,space_id:alternative.space_id});assert.equal(duplicate.status,200);assert.equal(duplicate.data.application_offer_id,chosen.data.application_offer_id);assert.equal(await offers(),before+1);
 const changed=await post({...body,space_id:alternative.space_id,rent:1300});assert.equal(changed.status,409);assert.equal(changed.data.error,'APPLICATION_OFFER_IDEMPOTENCY_CONFLICT');assert.equal(await offers(),before+1);
 const foreign=(await c.query("insert into properties(name) values('Owned foreign scope') returning id")).rows[0];
 const unit=(await c.query("insert into units(property_id,unit_number) values($1,'Foreign') returning id",[foreign.id])).rows[0];
 const foreignSpace=(await c.query('select id from spaces where unit_id=$1',[unit.id])).rows[0];
 const crossing=await post({...body,space_id:foreignSpace.id,idempotency_key:'owned-foreign',property_id:foreign.id});assert.equal(crossing.status,403);assert.equal(crossing.data.error,'SPACE_NOT_ON_PROPERTY');assert.equal(await offers(),before+1);
 const anonymous=await post(body,{});assert([401,403].includes(anonymous.status));assert.equal(await offers(),before+1);
 await c.query('update leases set end_date=$2 where id=$1',[f.ids.upcoming_lease,previousDay]);
 const correctedPriority=await rank(c,f.property_id);assert(correctedPriority.turns.some(t=>t.unit_id===home.unit_id),'chosen home must have a physical turn in this control');
 const restored=await post({...body,idempotency_key:'owned-corrected-rights'});assert.equal(restored.status,200,JSON.stringify(restored.data));assert.equal(restored.data.application_terms.target.space_id,home.space_id);
 assert.deepEqual(await rank(c,f.property_id),correctedPriority,'offering the actual in-progress turn must not create a lease commitment or priority');
 for(const name of ['I-future-pending','J-future-locked'])await c.query("insert into turnovers(property_id,unit_id,status) values($1,$2,'in_progress')",[f.property_id,f.units[name].unit_id]);
 const response=await fetch(process.env.E2E_API_BASE+'/operator/leasing/turn-priority',{headers:{'x-staff-session':session}});assert.equal(response.status,200);const priority=await response.json();
 const by=name=>priority.turns.find(t=>t.unit_id===f.units[name].unit_id);
 assert.equal(by('J-future-locked').demand_tier_key,'committed_start');assert.equal(by('I-future-pending').demand_tier_key,'pending_commitment');assert.equal(by('B-upcoming').demand_tier_key,'raw_vacancy');
 assert(by('J-future-locked').demand_tier>by('I-future-pending').demand_tier);assert(by('I-future-pending').demand_tier>by('B-upcoming').demand_tier);
 assert.equal(by('B-upcoming').commitment_start_date,null);assert.equal(by('B-upcoming').contributing_commitments.length,0);
 console.log('TURN_PRIORITY_HTTP: committed lease > pending lease > application offer; draft on a physical turn creates no deadline');
 console.log('OFFER_HTTP: conflicting rights + unknown readiness refused with rollback; competing home accepted; exact offer retry; changed terms refused; foreign/anonymous refused; corrected rights accepted; draft leaves maintenance priority unchanged');
};
