#!/usr/bin/env node
/*  ═══════════════════════════════════════════════════════════════════
 *  env_inventory.js — EVERY ENVIRONMENT VARIABLE THE CODE READS, WITH
 *  WHERE IT READS IT. CURRENT_STATE #25: 51 of 65 variables were documented
 *  nowhere. This does not guess what a variable means; it says which file
 *  reads it, so the reader can look. `.env.example` carries the meanings
 *  that are known; this inventory is the floor under it.
 *
 *      node tools/env_inventory.js            prints the inventory
 *      node tools/env_inventory.js --check    exits 1 if .env.example lacks a variable
 *  ═══════════════════════════════════════════════════════════════════ */
"use strict";
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "..");
const SCAN = ["server.js", "src", "migrations/migrate.js", "migrations/ledger_verdict.js", "tools"];
const found = new Map(); // name → Set(file:line)
function walk(p) {
  const st = fs.statSync(p);
  if (st.isDirectory()) { for (const e of fs.readdirSync(p)) if (e !== "node_modules") walk(path.join(p, e)); return; }
  if (!p.endsWith(".js")) return;
  const rel = path.relative(ROOT, p);
  fs.readFileSync(p, "utf8").split("\n").forEach((line, i) => {
    if (/^\s*\/\//.test(line)) return;
    for (const m of line.matchAll(/process\.env\.([A-Z][A-Z0-9_]+)/g)) {
      if (!found.has(m[1])) found.set(m[1], new Set());
      found.get(m[1]).add(`${rel}:${i + 1}`);
    }
    for (const m of line.matchAll(/process\.env\[["']([A-Z][A-Z0-9_]+)["']\]/g)) {
      if (!found.has(m[1])) found.set(m[1], new Set());
      found.get(m[1]).add(`${rel}:${i + 1}`);
    }
  });
}
for (const s of SCAN) if (fs.existsSync(path.join(ROOT, s))) walk(path.join(ROOT, s));
const names = [...found.keys()].sort();
const example = fs.existsSync(path.join(ROOT, ".env.example")) ? fs.readFileSync(path.join(ROOT, ".env.example"), "utf8") : "";
const documented = new Set([...example.matchAll(/^#?\s*([A-Z][A-Z0-9_]+)=/gm)].map((m) => m[1]));
const missing = names.filter((n) => !documented.has(n));
if (process.argv.includes("--check")) {
  if (missing.length) { console.error(`.env.example lacks ${missing.length} variable(s) the code reads: ${missing.join(", ")}`); process.exit(1); }
  console.log(`.env.example names every variable the code reads (${names.length}).`); process.exit(0);
}
console.log(`# ${names.length} environment variables read by server.js, src/, migrations/ and tools/ (generated by tools/env_inventory.js)`);
for (const n of names) console.log(`${n}\n#   read at ${[...found.get(n)].slice(0, 4).join(", ")}${found.get(n).size > 4 ? ` (+${found.get(n).size - 4} more)` : ""}`);
