const assert = require("assert");
const { prepareApplicationOffer, readApplicationOffer } = require("../../src/money/application_offer_terms");

const PROPERTY = "00000000-0000-0000-0000-000000000001";
const SPACE = "00000000-0000-0000-0000-000000000002";
const PERSON = "00000000-0000-0000-0000-000000000003";
const ACTING_PERSON = "00000000-0000-0000-0000-000000000005";
const ACTOR = { id: "00000000-0000-0000-0000-000000000004", user_id: "00000000-0000-0000-0000-000000000004", property_id: PROPERTY, can_manage_roles: true };
let saved;
let predecessorRow;
let successorRow;
let forceRetry = false;
let retryReading = false;
let governedCatalog = null;
const q = { async query(sql, args) {
  if (/from users u where u\.id/.test(sql)) return { rows: [{ id: ACTOR.id, person_id: ACTING_PERSON, account_kind: "human_staff", is_active: true, status: "active" }] };
  if (/count\(\*\)::int as n from users/.test(sql)) return { rows: [{ n: 1 }] };
  if (/personHasConflictingLinks/.test(sql)) return { rows: [] };
  if (/from assignments/.test(sql)) return { rows: [{ id: "assignment", role: "owner", is_active: true, property_id: PROPERTY, created_at: new Date() }] };
  if (/from property_team_assignments/.test(sql)) return { rows: [{ id: "team", active: true, can_manage_roles: true }] };
  if (/from concession_authority_grants/.test(sql)) return { rows: [] };
  if (/from property_governed_charges/.test(sql)) {
    const source = governedCatalog ? [...(governedCatalog.one_time_fees || []), ...(governedCatalog.recurring_charges || []), ...(governedCatalog.deposit_requirements || [])] : [];
    return { rows: source.map((c) => ({ ...c, id: c.charge_id, display_label: c.charge_code, record_state: "active", quote_state: c.quotable_precisely === false ? "inactive" : "live", effective_from: "2020-01-01", published_by: "staff" })) };
  }
  if (/select id from properties/.test(sql)) return { rows: [{ id: PROPERTY }] };
  if (/select id from persons/.test(sql)) return { rows: [{ id: PERSON }] };
  if (/select id from lease_applications/.test(sql)) return { rows: args[0] === "application-1" ? [{ id: "application-1" }] : [] };
  if (/select\s+exists \(select 1 from leases/.test(sql)) return { rows: [{ has_active_lease: false, has_pending_lease: false, has_application: false, has_presence: true }] };
  if (/select s\.id, s\.unit_id/.test(sql)) return { rows: args[0] === SPACE ? [{ id: SPACE, unit_id: "00000000-0000-0000-0000-000000000006" }] : [] };
  if (/space_id=\$4 and source='application_proposal' for update/.test(sql)) return { rows: args[0] === (successorRow && successorRow.id) ? [successorRow] : (predecessorRow ? [predecessorRow] : []) };
  if (/select id from lease_offers where id=\$1 and source='application_proposal'/.test(sql)) return { rows: args[0] === (saved && saved.id) || args[0] === (successorRow && successorRow.id) ? [{ id: args[0] }] : [] };
  if (/supersedes_application_offer_id=\$1/.test(sql)) return { rows: successorRow && args[0] === successorRow.supersedes_application_offer_id ? [successorRow] : [] };
  if (/select \* from lease_offers/.test(sql)) return { rows: forceRetry && args[3] === "retry-key" && !retryReading ? [] : (["successor-1", "successor-2"].includes(args[3]) ? [] : (saved ? [saved] : [])) };
  if (/insert into lease_offers/.test(sql)) { if (forceRetry) { retryReading = true; return { rows: [] }; } const authority = JSON.parse(args[6]); const row = { id: args[4] ? (authority.idempotency_key === "successor-2" ? "00000000-0000-0000-0000-000000000009" : "00000000-0000-0000-0000-000000000008") : "00000000-0000-0000-0000-000000000007", property_id: PROPERTY, person_id: PERSON, application_id: args[2], space_id: SPACE, supersedes_application_offer_id: args[4], source: "application_proposal", status: "draft", offered_terms_snapshot: JSON.parse(args[5]), authority_basis_snapshot: authority }; if (args[4]) successorRow = row; else saved = row; return { rows: [row] }; }
  throw new Error(`unexpected SQL: ${sql}`);
} };
const input = { actor: ACTOR, person_id: PERSON, space_id: SPACE, lease_start_date: "2026-10-01", lease_end_date: "2027-09-30", rent: 1200, security_deposit: 0, fees: [], concessions: { status: "none" }, idempotency_key: "offer-1" };

(async () => {
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, rent: null }), /rent is required/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, rent: true }), /rent is required/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, rent: [1200] }), /rent is required/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, rent: 1200.005 }), /two decimal places/);
  const cents = await prepareApplicationOffer(q, { ...input, rent: 0.29, idempotency_key: "decimal-cents" });
  assert.equal(cents.application_terms.rent, "0.29", "valid cents survive binary floating point representation");
  saved = null;
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, lease_end_date: "2026-02-30" }), /real calendar date/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, fees: undefined }), /fees must be an explicit array/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, fees: [{ code: "admin", label: "Admin", amount: 10, cadence: "weekly" }] }), /cadence is unsupported/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, fees: [{ code: "admin", label: "Admin", amount: 10, cadence: "monthly" }, { code: "admin", label: "Admin again", amount: 5, cadence: "one_time" }] }), /code must be unique/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, concessions: { status: "structured" } }), /structured concessions/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, space_id: "00000000-0000-0000-0000-000000000099" }), /does not belong/);
  governedCatalog = { one_time_fees: [{ charge_id: "charge-1", charge_code: "fee.application", economic_class: "one_time_fee", amount: 50, cadence: "one_time", obligation: "required", applicability_scope: "property", applies_to_new_lease: true, effective_now: true, quotable_precisely: true, assessed_per: "applicant" }], recurring_charges: [], deposit_requirements: [] };
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, idempotency_key: "missing-fee" }), /must be included/);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, idempotency_key: "wrong-fee", fees: [{ code: "fee.application", label: "Application fee", amount: 40, cadence: "per_applicant" }] }), /does not match/);
  governedCatalog = { one_time_fees: [{ ...governedCatalog.one_time_fees[0], obligation: "optional", cadence: "annual" }], recurring_charges: [], deposit_requirements: [] };
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, idempotency_key: "unsupported-catalog-cadence", fees: [] }), /unsupported cadence/);
  governedCatalog = { one_time_fees: [{ ...governedCatalog.one_time_fees[0], cadence: "one_time", amount: 25 }], recurring_charges: [], deposit_requirements: [] };
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, idempotency_key: "optional-wrong-fee", fees: [{ code: "fee.application", label: "Application fee", amount: 20, cadence: "per_applicant" }] }), /does not match/);
  governedCatalog = { one_time_fees: [{ ...governedCatalog.one_time_fees[0], amount: 50, obligation: "required" }], recurring_charges: [], deposit_requirements: [] };
  const zeroCatalog = { ...governedCatalog, one_time_fees: [{ ...governedCatalog.one_time_fees[0], amount: 0 }] };
  governedCatalog = zeroCatalog;
  const zero = await prepareApplicationOffer(q, { ...input, idempotency_key: "zero-fee", fees: [{ code: "fee.application", label: "Application fee", amount: 0, cadence: "per_applicant" }] });
  assert.equal(zero.application_terms.fees[0].amount, "0.00");
  assert.equal(zero.application_terms.fees[0].governed_charge_id, "charge-1");
  assert.equal(zero.application_terms.fees[0].source, "property_governed_charges");
  saved = null;
  governedCatalog = { one_time_fees: [{ ...governedCatalog.one_time_fees[0], amount: null, quotable_precisely: false }], recurring_charges: [], deposit_requirements: [] };
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, idempotency_key: "unresolved-fee", fees: [{ code: "fee.application", label: "Application fee", amount: 0, cadence: "per_applicant" }] }), /no precise quotable terms/);
  governedCatalog = null;
  const made = await prepareApplicationOffer(q, input);
  assert.equal(made.offer.status, "draft");
  assert.equal(made.application_terms.security_deposit, "0.00");
  assert.equal(made.application_terms.fees.length, 0);
  const replay = await prepareApplicationOffer(q, input);
  assert.equal(replay.idempotent, true);
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, application_id: "application-1" }), /different application terms/);
  forceRetry = true;
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, idempotency_key: "retry-key", application_id: "application-1" }), /different application terms/);
  forceRetry = false;
  await assert.rejects(() => prepareApplicationOffer(q, { ...input, rent: 1300 }), /different application terms/);
  predecessorRow = { ...saved, application_id: "application-1" };
  const successor = await prepareApplicationOffer(q, { ...input, idempotency_key: "successor-1", application_id: "application-1", supersedes_application_offer_id: saved.id });
  assert.equal(successor.offer.supersedes_application_offer_id, saved.id);
  assert.equal(successor.offer.authority_basis_snapshot.supersedes_application_offer_id, saved.id);
  await assert.rejects(() => require("../../src/money/application_offer_terms").assertCurrentApplicationOffer(q, saved.id), /superseded/);
  const successor2 = await prepareApplicationOffer(q, { ...input, idempotency_key: "successor-2", application_id: "application-1", supersedes_application_offer_id: successor.offer.id });
  assert.equal(successor2.offer.supersedes_application_offer_id, successor.offer.id);
  assert.equal((await readApplicationOffer(q, { offer_id: saved.id, property_id: PROPERTY, person_id: PERSON, space_id: SPACE })).offer_id, saved.id);
  saved.expires_at = new Date(Date.now() - 1000).toISOString();
  await assert.rejects(() => readApplicationOffer(q, { offer_id: saved.id, property_id: PROPERTY, person_id: PERSON, space_id: SPACE }), /expired/);
  console.log("application_offer_terms: PASS");
})().catch((e) => { console.error(e); process.exit(1); });
